name = "demo-durable-objects-worker"
main = "src/worker.ts"
compatibility_date = "2023-09-01"

[durable_objects]
bindings = [{ name = "store", class_name = "Store" }]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Store"]
